### ISSUE TITLE
Add SECURITY.md

### ISSUE THREAD

**Issue by JamieSlome** [liukuo362573/YiShaAdmin#108]
Hey there!

I belong to an open source security research community, and a member (@khanhchauminh) has found an issue, but doesn’t know the best way to disclose it.

If not a hassle, might you kindly add a `SECURITY.md` file with an email, or another contact method? GitHub [recommends](https://docs.github.com/en/code-security/getting-started/adding-a-security-policy-to-your-repository) this best practice to ensure security issues are responsibly disclosed, and it would serve as a simple instruction for security researchers in the future.

Thank you for your consideration, and I look forward to hearing from you!

(cc @huntr-helper)

**Comment by smartdust007** [comment]
I have got your e-mail,This is an automatic reply to let you know that your mail has been received.Thank you.---Wang Shupeng

**Comment by liukuo362573** [comment]
@JamieSlome I add a SECURITY.md file now , thank your team for contribution.

**Comment by JamieSlome** [comment]
@liukuo362573 - please do not share the long URL as this will allow anyone to act on behalf of you.

I have redacted this magic URL access and issued a new one. Feel free to remove the URL from your security policy as it now does not work.

Thank you for your contributions as well!
