### ISSUE TITLE
按钮权限有问题

### ISSUE THREAD

**Issue by gywei** [liukuo362573/YiShaAdmin#12]
按钮权限有问题，系统没有实现按钮权限管控吧？虽然后台有配置启用禁用，但是实际没有效果。

**Comment by liukuo362573** [comment]
系统是按角色来管理权限的，控制到按钮级别，你说的这个应该是菜单页面的按钮启用禁用，我刚测试了一下，这个是个bug。

**Comment by liukuo362573** [comment]
> 按钮权限有问题，系统没有实现按钮权限管控吧？虽然后台有配置启用禁用，但是实际没有效果。

系统是按角色来管理权限的，控制到按钮级别，你说的这个应该是菜单页面的按钮启用禁用，我刚测试了一下，这个是个bug。
