### ISSUE TITLE
运行出现个问题

### ISSUE THREAD

**Issue by wqqwqq666** [liukuo362573/YiShaAdmin#14]
报下面的问题
![图片](https://user-images.githubusercontent.com/15796964/77130278-44303180-6a92-11ea-95a5-8a0561667f90.png)

**Comment by liukuo362573** [comment]
这个错误我也遇到过，不经常出现，我就没管它了。

**Comment by liukuo362573** [comment]
@wqqwqq666 这个错误我也遇到过，不经常出现，我就没管它了。

**Comment by liukuo362573** [comment]
这个已经解决了。https://github.com/liukuo362573/YiShaAdmin/commit/56d32d61152e03fffbe065b11dc3b293e33ceed3
