### ISSUE TITLE
自动生成的网址错误

### ISSUE THREAD

**Issue by Witchie** [liukuo362573/YiShaAdmin#17]
在菜单管理里面新增一个页面，地址

`http://www.hao123.com`,

最终生成的网址为

`http://localhost:80/http://www.hao123.com`
很明显前置URI不该添加。

**Comment by liukuo362573** [comment]
已修复，谢谢反馈。

**Comment by liukuo362573** [comment]
已修复，谢谢反馈。 @Witchie
