### ISSUE TITLE
作者有没有计划出个依赖注入为主版本的后台

### ISSUE THREAD

**Issue by SmallDrogan** [liukuo362573/YiShaAdmin#20]
这里三层架构非常清晰，项目结构很清晰，但是感觉跟微软主推的初衷有背，AspNetCore主推依赖注入aop的开发方式，但看项目感觉完全像是撇开依赖注入。强行还是原来net framework的开发模式。

**Comment by liukuo362573** [comment]
你说的一半是对的，依赖注入首先需要的是接口，接口会增加系统的复杂性，所以业务层BLL和服务层Service都没有增加任何接口层，目前来看，只能把数据库和缓存用依赖注入的方式去配置。

**Comment by SmallDrogan** [comment]
好的，点个star 以表支持 。
