### ISSUE TITLE
工程内的表格单元格样式设置不起作用

### ISSUE THREAD

**Issue by helloworld88888888** [liukuo362573/YiShaAdmin#23]
在列初始化时设置单元格样式：
                        cellStyle:function(value,row,index){  
                        	    if (value=="11"){  
                                    return { css: { "background-color": "#00E400" } };  
                        	    }else {   
                                    return { css: { "background-color": "#7E0023" } };  
                        	    }  
                        }   
在工程外单独的测试页面中可以按值设置背景颜色，但在本项目中设置不起作用。
工程外：
![正常](https://user-images.githubusercontent.com/65161156/81546712-5c933d00-93ad-11ea-89de-b86287444d36.PNG)

本项目：
背景色不起作用

**Comment by liukuo362573** [comment]
谢谢反馈，问题已修复，background-color被覆盖了。
