### ISSUE TITLE
表格多字段排序时，只有一个起作用

### ISSUE THREAD

**Issue by helloworld88888888** [liukuo362573/YiShaAdmin#24]
排序设置：
			sortOrder: 'asc',
			sortName: 'ReportTime,AqiValue,Pm25Iaqi,Pm10Iaqi',
实际只有最后一个有效。
我的办法：
修改数据库排序字段处理，sqlserver修改：SqlServerDatabase.cs 下
private async Task<(int total, IEnumerable<T> list)> FindList<T>(IQueryable<T> tempData, string orderField, bool isAsc, int pageSize, int pageIndex)

                if(index==0 )
                    resultExp = Expression.Call(typeof(Queryable), isAsc ? "OrderBy" : "OrderByDescending", new Type[] { typeof(T), property.PropertyType }, tempData.Expression, Expression.Quote(orderByExp));
                else
                    resultExp = Expression.Call(typeof(Queryable), isAsc ? "ThenBy" : "OrderByDescending", new Type[] { typeof(T), property.PropertyType }, resultExp, Expression.Quote(orderByExp));

**Comment by liukuo362573** [comment]
谢谢你的反馈，回头我会根据你这个修改一下。
