### ISSUE TITLE
新建表后代码生成器生成后提示列名无效，请留意列名是否以带下划线命名user_name

### ISSUE THREAD

**Issue by archerzhaopan** [liukuo362573/YiShaAdmin#27]
新建表后代码生成器生成后提示列名无效，请留意列名是否以带下划线命名user_name

SELECT TOP 1000 [Id]
      ,[UserName]
      ,[TelPhone]
      ,[IdCard]
      ,[Creatime]
  FROM [PingAnUserMsg]
我数据库新建了一个表，然后用代码生成器生成了文件后，提示出我列名 'id_card' 无效。 列名 'tel_phone' 无效。 列名 'user_name' 无效
-----------------------------------

解决方案是：按文档的命名，字段命带下划线

**Comment by liukuo362573** [comment]
为了方便处理，现在数据表和实体之间的命名保持一致。
