### ISSUE TITLE
mysql_update_column_name.sql似乎无法更新字段和表名的下划线还是原来的样子

### ISSUE THREAD

**Issue by jhzou1** [liukuo362573/YiShaAdmin#32]
mysql_update_column_name.sql似乎无法更新字段和表名的下划线还是原来的样子。

**Comment by liukuo362573** [comment]
脚本里面需要指定一个数据库，看看是不是数据库没有指定。

**Comment by jhzou1** [comment]
是的数据库已经设置选定指定数据库，但是似乎脚本无效
![image](https://user-images.githubusercontent.com/51555104/82965962-3f40ae80-9ffc-11ea-96e7-16c6d790129a.png)

**Comment by liukuo362573** [comment]
脚本里面只加入了框架需要的表，其他的表要自己加。。

**Comment by jhzou1** [comment]
哦，看到了，谢谢
