### ISSUE TITLE
EXCELHELP数据类型缺失

### ISSUE THREAD

**Issue by ajancn** [liukuo362573/YiShaAdmin#34]
导出excel的时候，real类型数据导出为空白，请在EXCELHELPER，建议增加单精类型，和其他类型。
                        case "System.Single":
                        case "System.Nullable`1[System.Single]":
                            newCell.SetCellValue(drValue.ParseToFloat());
                            break;

**Comment by liukuo362573** [comment]
谢谢反馈，麻烦提个pull request，因为我的测试毕竟有限。
