### ISSUE TITLE
启动不了项目是扫码情况？ 

### ISSUE THREAD

**Issue by vx54409617** [liukuo362573/YiShaAdmin#44]
E:\NETCore\YiShaAdmin\YiSha.Web\YiSha.Admin.Web\bin\Debug\netcoreapp3.1>dotnet YiSha.Admin.Web.exe
Error:
  An assembly specified in the application dependencies manifest (YiSha.Admin.Web.deps.json) has already been found but with a different file extension:
    package: 'YiSha.Admin.Web', version: '1.0.0'
    path: 'YiSha.Admin.Web.dll'
    previously found assembly: 'E:\NETCore\YiShaAdmin\YiSha.Web\YiSha.Admin.Web\bin\Debug\netcoreapp3.1\YiSha.Admin.Web.exe'

**Comment by liukuo362573** [comment]
@vx54409617  看不懂标题
