### ISSUE TITLE
新增第三方JS组件如何生效的问题

### ISSUE THREAD

**Issue by Dalbhid** [liukuo362573/YiShaAdmin#45]
如题，如何让自己加的第三方组件在yisha中生效。我的做法是首先在lib中加入JS组件包，
然后在头部引入文件比如：
`@inject Microsoft.AspNetCore.Hosting.IWebHostEnvironment HostingEnvironment
@section header{
    @BundlerHelper.Render(HostingEnvironment.ContentRootPath, Url.Content("~/lib/typeahead/bootstrap3-typeahead.min.js"))
    @BundlerHelper.Render(HostingEnvironment.ContentRootPath, Url.Content("~/lib/reorder/bootstrap-table-reorder.js"))
    @BundlerHelper.Render(HostingEnvironment.ContentRootPath, Url.Content("~/lib/reorder/jquery.tablednd.js"))
}`
然后去代码中调用，发现是不生效的，不知道还需要哪里做设置。

但是如果我在body底部用常规方法引入是生效的，比如：
`<script src="~/lib/typeahead/bootstrap3-typeahead.min.js"></script><script src="~/lib/reorder/bootstrap-table-reorder.js"></script><script src="~/lib/reorder/jquery.tablednd.js"></script>`
求大佬解惑一下是否我哪里设置出错或遗漏了什么？Tks

**Comment by liukuo362573** [comment]
BundlerHelper实际引用的是bundleconfig.json里面的js，如果js不存在，生成的html里面自然没有那个js。

**Comment by Dalbhid** [comment]
> BundlerHelper实际引用的是bundleconfig.json里面的js，如果js不存在，生成的html里面自然没有那个js。

好的，谢谢大佬，已经解决！Tks
