### ISSUE TITLE
请问下，net core 3.1 好像不支持，是么？

### ISSUE THREAD

**Issue by afowne** [liukuo362573/YiShaAdmin#47]
It was not possible to find any compatible framework version
The framework 'Microsoft.AspNetCore.App', version '2.2.0' was not found.
  - The following frameworks were found:
      2.1.17 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
      3.1.3 at [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.AspNetCore.App&framework_version=2.2.0&arch=x64&rid=win10-x64

C:\Program Files\dotnet\dotnet.exe (进程 10892)已退出，代码为 -2147450730。
要在调试停止时自动关闭控制台，请启用“工具”->“选项”->“调试”->“调试停止时自动关闭控制台”。
按任意键关闭此窗口. . .

**Comment by liukuo362573** [comment]
支持的，可能是你的环境问题

**Comment by afowne** [comment]
> 支持的，可能是你的环境问题

好的，谢谢，我再检查下

**Comment by afowne** [comment]
> > 支持的，可能是你的环境问题
> 
> 好的，谢谢，我再检查下
不好意思，没有看仔细，下载了2.2的版本，使用3.1后已经可以
