### ISSUE TITLE
bootstrap tree 扩展有问题

### ISSUE THREAD

**Issue by apgk** [liukuo362573/YiShaAdmin#5]
举个例子：
列表数据是A->B->C  这样tree类型可以显示A 的parentId=0或者null

如果搜索完数据是B->C 无法显示 B的parentId是AId,但此时A不在，一直找不到，造成最后无法显示数据
bootstrap-treetable.js 里面 formatData--->target.getRootFlag(item);

**Comment by liukuo362573** [comment]
已修复，见changeset
