### ISSUE TITLE
表关联查询及新增

### ISSUE THREAD

**Issue by zhongshuiyuan** [liukuo362573/YiShaAdmin#53]
请问如何使用框架进行有外键关联或者普通的表关联增删改查，必须要自己在相应的区域进行多个BLL操作吗？

**Comment by liuyongtao** [comment]
这个就是EFcore的缺点了，要使用Linq来做

**Comment by liuyongtao** [comment]
![Uploading QQ截图20201109113903.png…]()


看代码，有写sql查询的地方，通过sql可以连表查

**Comment by zhongshuiyuan** [comment]
我目前就是这样做的，比较麻烦些
