### ISSUE TITLE
SqlServerDatabase.Update<T>(IEnumerable<T> entities) 批量更新数据方法报错

### ISSUE THREAD

**Issue by kuyu05** [liukuo362573/YiShaAdmin#57]
### Overview of the problem
使用SqlServer数据库，批量更新数据时，Update功能报错。

### Description
Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances. Object name: 'SqlServerDbContext'.

### Steps to reproduce
1. List<Entity> entity;
2. service.Update(entity);

### The problem code
https://github.com/liukuo362573/YiShaAdmin/blob/master/YiSha.Data/YiSha.Data.EF/Database/SqlServerDatabase.cs
line257。
```
foreach (var entity in entities)
{
    await this.Update(entity); // line257
}
```
这里第一次执行`await this.Update(entity);`后，就会关闭事务，导致后续操作报错。
与`Insert`的写法有差别。Line167。

**Comment by liukuo362573** [comment]
谢谢反馈
