### ISSUE TITLE
权限上有问题

### ISSUE THREAD

**Issue by apgk** [liukuo362573/YiShaAdmin#6]
例如用户管理
A公司
---B部门
-----B1员工
---C部门

B1有用户管理菜单权限，
左侧菜单就会显示
A公司
---B部门
---C部门
右侧列表会显示所有用户

其实真正上应该显示最顶级是B部门或者A公司右侧的用户也不能显示所有，毕竟不是超级管理员。这样造成越权修改一些信息了，任何一个有用户管理菜单权限的都能把用户随意创建到任意部门或者公司下面去。

**Comment by liukuo362573** [comment]
框架实现了一个基础的功能，更详细的业务需要自己实现。
