### ISSUE TITLE
GetIpLocationFromPCOnline 出现bug，不支持 GB2312

### ISSUE THREAD

**Issue by jhzou1** [liukuo362573/YiShaAdmin#65]
HttpResult httpResult = new HttpHelper().GetHtml(new HttpItem
            {
                URL = "http://whois.pconline.com.cn/ip.jsp?ip=" + ipAddress,
                ContentType = "text/html; charset=gb2312"
            });

![image](https://user-images.githubusercontent.com/51555104/103055711-fa064e80-45d5-11eb-8e25-116900ac86f4.png)

目前解决方法，引入System.Text.Encoding.CodePages 包
在使用 GB2312之前执行下面的代码。
System.Text.Encoding.RegisterProvider(System.Text.CodePagesEncodingProvider.Instance);

**Comment by liukuo362573** [comment]
好的，谢谢反馈
