### ISSUE TITLE
我觉得这部分代码应该改进一下

### ISSUE THREAD

**Issue by zy5717297** [liukuo362573/YiShaAdmin#68]
/*以下代码可能需要改进，这只是其中一个例子，建议作者全盘检查一下*/
/* UserService.cs 第193行 */
//if (!string.IsNullOrEmpty(param.EndTime.ParseToString()))
//{
//    param.EndTime = (param.EndTime.Value.ToString("yyyy-MM-dd") + " 23:59:59").ParseToDateTime();
//    expression = expression.And(t => t.BaseModifyTime <= param.EndTime);
//}

/*建议这么做*/
if (param.EndTime.HasValue)
{
    var endTime = param.EndTime.Value.Date.Add(new TimeSpan(23, 59, 59));
    param.EndTime = endTime;
    expression = expression.And(t => t.BaseModifyTime <= param.EndTime);
}

**Comment by zhongshuiyuan** [comment]
能开源代码就已经不错了，发现代码质量问题，你自己可以修改或者建议修改，没必要攻击

**Comment by liukuo362573** [comment]
@zy5717297 有些代码可能质量不高，毕竟水平和精力都有限，开源出来也是为了更多人能够学习交流进步。学习当然也可以从别人的不好的地方学习。
本来一个很好的问题，像你这样的质疑与建议方式，换位思考一下，如果对方这样和你建议，你会接受吗，做人做事还是要善意一些。

**Comment by liukuo362573** [comment]
@zy5717297 谢谢改动，测试了一下，用你的方式执行时间更短。
