### ISSUE TITLE
字符串字段保存时空值无法更新旧值。

### ISSUE THREAD

**Issue by computerWu158** [liukuo362573/YiShaAdmin#7]
所有的表均存在此问题：用户在更新一个表的字符串字段时，若该字段原先有字符串值，修改为空，则无法保存空值。原值不变。 需把空值改为 string.Empty。（ 用户的备注信息字段无法保存。）

**Comment by liukuo362573** [comment]
详细可以参考这个链接，https://stackoverflow.com/questions/44376540/asp-net-core-model-binding-how-to-get-empty-field-to-bind-as-a-blank-string
