### ISSUE TITLE
导出excle时如果一个单元个数据长度大于255个字符报错

### ISSUE THREAD

**Issue by fangxin810425** [liukuo362573/YiShaAdmin#94]
ExcelHelper.cs

//根据单元格内容设定列宽
int length = (System.Text.Encoding.UTF8.GetBytes(drValue).Length+1)*256;
修改为
//根据单元格内容设定列宽
 int length = (Math.Min(253, System.Text.Encoding.UTF8.GetBytes( drValue).Length+1))*256;

**Comment by liukuo362573** [comment]
好的，回头我试试
